language: python
python:
- '2.7'
- '3.6'
before_install:
- pip install pytest pytest-cov
- pip install coveralls
- pip install flask flask-restful jsonfy
install:
- nohup FLASK_APP=ObsDataRest.py flask run &
script:
- pytest .
