language: python
python:
  - '3.6'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
script:
  - coverage run --source=ObsDataRest -m pytest .
after_success:
  - coveralls
before_install:
  - openssl aes-256-cbc -K $encrypted_9c98d1b39b99_key -iv $encrypted_9c98d1b39b99_iv
    -in deploy_rsa.enc -out deploy_rsa -d
