language: python
python:
- '3.6'
before_install:
install:
- pip install flask flask-restful requests pytest-ordering
- pip install pytest-cov coveralls
- python create_db.py
- python run.py &
- sleep 2
script:
- pytest .
after_success:
- coverage run -m pytest .
- coveralls
