language: python
python:
- '3.6'
before_install:
install:
- pip install  python-dateutil flask flask-restful flask-sqlalchemy pytest-ordering pytest-env
- pip install coverage coveralls
script:
- coverage run --source=ObsDataRest -m pytest .
after_success:
- coveralls
