language: python
python:
- '3.6'
before_install:
install:
- pip install flask flask-restful pytest-ordering
- pip install coverage coveralls
before_script:
- python create_db.py
script:
- coverage run --source=ObsDataRest -m pytest .
after_success:
- coveralls
