language: python
python:
- '3.6'
before_install:
install:
- pip install flask flask-restful pytest-ordering
- pip install coverage coveralls
script:
- coverage run --source=ObsDataRest -m ObsDataRest/create_database.py
- coverage run --source=ObsDataRest -m pytest .
after_success:
- coveralls
