language: python
python:
- '3.6'
before_install:
install:
- pip install flask flask-restful requests pytest-ordering
- pip install pytest-cov coveralls
script:
- coverage run --append --source=ObsDataRest run.py -c &
- sleep 2
- coverage run -a --source=ObsDataRest -m pytest .
after_success:
- coveralls
